In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
sampleSub = pd.read_csv("sampleSubmission.csv")

In [3]:
test = pd.read_csv('test.csv')
train = pd.read_csv('train.csv')

In [35]:
train.head()

S1  C1  S2  C2  S3  C3  S4  C4  S5  C5  hand
0   4   9   2   1   2   2   4   7   2   8     0
1   1   4   3   6   1  12   3  11   2   7     0
2   1  11   4   1   3   7   4  11   2   1     2
3   2   9   2   4   3   6   1   9   4   9     3
4   1   8   2   4   2  11   2   2   2   1     0

In [36]:
test.head()

id  S1  C1  S2  C2  S3  C3  S4  C4  S5  C5
0   1   1  10   2   2   3   3   3   8   1   1
1   2   2  13   3   5   3   7   4   6   1   4
2   3   1   3   1  11   2   8   2   1   2   4
3   4   1   6   3   3   4   7   1   8   3  11
4   5   2  10   3   4   1   6   2  12   2   6

In [22]:
x = train.drop('hand',axis=1)
y = train['hand']

In [32]:
x.head()

S1  C1  S2  C2  S3  C3  S4  C4  S5  C5
0   4   9   2   1   2   2   4   7   2   8
1   1   4   3   6   1  12   3  11   2   7
2   1  11   4   1   3   7   4  11   2   1
3   2   9   2   4   3   6   1   9   4   9
4   1   8   2   4   2  11   2   2   2   1

In [34]:
y.head()

0    0
1    0
2    2
3    3
4    0
Name: hand, dtype: int64

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [24]:
from sklearn.neural_network import MLPClassifier
classifier = MLPClassifier(hidden_layer_sizes=(200,150,100),activation='relu')

In [25]:
classifier.fit(X_train,y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(200, 150, 100), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [26]:
classifier.score(X_test, y_test)

0.92502998800479808

In [27]:
pred = classifier.predict(X_test)

In [28]:
from sklearn.metrics import classification_report,confusion_matrix

In [29]:
print(classification_report(pred,y_test))

             precision    recall  f1-score   support

          0       0.99      0.94      0.96      2615
          1       0.93      0.93      0.93      2167
          2       0.46      0.75      0.57       141
          3       0.59      0.78      0.67        73
          4       0.08      0.40      0.13         5
          5       0.00      0.00      0.00         0
          6       0.00      0.00      0.00         0
          7       1.00      1.00      1.00         1
          8       0.00      0.00      0.00         0
          9       0.00      0.00      0.00         0

avg / total       0.94      0.93      0.93      5002



/root/anaconda2/envs/ipykernel_py3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [30]:
print(confusion_matrix(pred,y_test))

[[2455  134    0    0   15   10    0    0    0    1]
 [  27 2006  111   12    8    0    0    0    1    2]
 [   0    5  106   28    0    0    2    0    0    0]
 [   0    0   13   57    0    0    3    0    0    0]
 [   1    2    0    0    2    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    1    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]]


In [19]:
Test = test.drop('id',axis=1)

In [20]:
Test.head()

S1  C1  S2  C2  S3  C3  S4  C4  S5  C5
0   1  10   2   2   3   3   3   8   1   1
1   2  13   3   5   3   7   4   6   1   4
2   1   3   1  11   2   8   2   1   2   4
3   1   6   3   3   4   7   1   8   3  11
4   2  10   3   4   1   6   2  12   2   6

In [21]:
classifier.fit(x,y)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(200, 125, 100), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [10]:
pred = classifier.predict(Test)

In [11]:
pred = pd.DataFrame(pred)
sampleSub['hand'] = pred

In [12]:
sampleSub.to_csv('sumbit.csv',index=False)